### ISSUE TITLE
org.freedesktop.Platform//20.08 is end-of-life

### ISSUE THREAD

**Issue by billyswong** [flathub/org.freedesktop.adriconf#2]
When I run `flatpak update`, flatpak complains org.freedesktop.adriconf is using end-of-life runtimes, namely org.freedesktop.Platform//20.08 and org.freedesktop.Platform.GL.default//20.08

Could adriconf be repackaged to eliminate this error?

**Comment by jlHertel** [comment]
Hi @billyswong 
Yes for sure. I just published an update (2.5.1) using the latest SDK. It will take some time for Flathub to make the change available (I think 8 hours +), so unfortunately you will have to wait.

**Comment by jlHertel** [comment]
The change has been published on 20th of November as I described above. 
Thanks for reporting this issue, the contribution is appreciated.

I'm going to close this issue. If you need further help or wanna discuss more, feel free to open a new issue.
